-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer,
    username character varying(50) NOT NULL,
    created date,
    PRIMARY KEY (user_id),
    CONSTRAINT username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.photos
(
    photo_id integer,
    url character varying(100),
    user_id integer,
    created date,
    PRIMARY KEY (photo_id)
);

CREATE TABLE IF NOT EXISTS public.likes
(
    user_id integer,
    photo_id integer,
    likedate date,
    PRIMARY KEY (user_id, photo_id)
);

CREATE TABLE IF NOT EXISTS public.follow
(
    follower_id integer,
    followed_person_id integer,
    follow_date date,
    PRIMARY KEY (follower_id, followed_person_id)
);

ALTER TABLE IF EXISTS public.photos
    ADD CONSTRAINT user_id FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.likes
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.likes
    ADD FOREIGN KEY (photo_id)
    REFERENCES public.photos (photo_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.follow
    ADD FOREIGN KEY (follower_id, followed_person_id)
    REFERENCES public.users (user_id, user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
